### ISSUE TITLE
Heroku not hosting Angular properly

### ISSUE THREAD

**Issue by fhb4061** [fhb4061/FAQ_chatbot_25#7]
![herokunotworking](https://user-images.githubusercontent.com/21212346/40396983-495f9dd8-5e84-11e8-9798-801ac7c4e72d.PNG)

This is whats shown when trying to launch the application after pushing up to Github. Changes made only to package.json and created a server,js file to tell heroku what to do when deployed

**Comment by fhb4061** [comment]
![heroku debugging](https://user-images.githubusercontent.com/21212346/40399269-8bc8a118-5e90-11e8-8fa3-b7322199a03f.PNG)

This is whats shown when looking through the logs. Says the app crashed as well as reference error

**Comment by fhb4061** [comment]
![heroku result](https://user-images.githubusercontent.com/21212346/40399817-7cc05898-5e93-11e8-92a1-7a42d8ea996f.PNG)

This is whats shown on Heroku

![heroku bug](https://user-images.githubusercontent.com/21212346/40399743-352f719e-5e93-11e8-8bbb-ae615ee88a13.PNG)

Managed to correct the package.json file, but now server.js file is wrong. I'll be updating it to have the right directory and see if it'll work.

**Comment by fhb4061** [comment]
![bug tracking](https://user-images.githubusercontent.com/21212346/40400650-39fe26b2-5e97-11e8-9820-05f963cddf79.PNG)

What is shown on the Heroku app

**Comment by fhb4061** [comment]
![cannot get](https://user-images.githubusercontent.com/21212346/40402068-c3eb3594-5e9d-11e8-8b53-d6bffaec8780.PNG)

I removed the needing of a path to redirect files to - Which is going into a simpler way of hosting it on Heroku. This issue came up instead - I'm think its passing https which angular isn't supporting?

**Comment by fhb4061** [comment]
@ericlam1995  can you suggest a solution for this?

**Comment by thilam1995** [comment]
@fhb4061 let me deal, I will test my one.

**Comment by thilam1995** [comment]
@fhb4061 take a look how it work on my one. https://faqchatbot25-test.herokuapp.com/

**Comment by thilam1995** [comment]
Here a solution I found: https://github.com/gdi2290/angular-starter/issues/1671
@fhb4061

**Comment by fhb4061** [comment]
![heroku_solution](https://user-images.githubusercontent.com/21212346/40450720-9a3e3a82-5f30-11e8-8dcd-b4b524cca7a8.PNG)

Thank you @ericlam1995 This was the solution for Fixing this bug.
